version: '3.8'

services:
  fastapi:
    build:
      context: .  # Контекст сборки для fastapi (корневая директория)
      dockerfile: app/Dockerfile  # Путь к Dockerfile для fastapi
    volumes:
      - app_data:/app  # Монтируем общий том
    ports:
      - "8000:8000"

  bot:
    build:
      context: .  # Контекст сборки для bot (корневая директория)
      dockerfile: bot/Dockerfile  # Путь к Dockerfile для bot
    volumes:
      - app_data:/bot  # Монтируем общий том

volumes:
  app_data:
    driver: local
