"""change_liquid

Revision ID: 17b7489a0177
Revises: 34d09003b5b2
Create Date: 2024-10-15 21:51:16.125215

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "17b7489a0177"
down_revision: Union[str, None] = "34d09003b5b2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "liquid", sa.Column("current_free", sa.Integer(), nullable=True)
    )
    op.add_column(
        "liquid", sa.Column("current_coins", sa.Integer(), nullable=True)
    )
    op.add_column(
        "liquid", sa.Column("current_money", sa.Integer(), nullable=True)
    )
    op.add_column(
        "liquid", sa.Column("current_stars", sa.Integer(), nullable=True)
    )
    op.add_column(
        "liquid", sa.Column("current_token", sa.Integer(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("liquid", "current_token")
    op.drop_column("liquid", "current_stars")
    op.drop_column("liquid", "current_money")
    op.drop_column("liquid", "current_coins")
    op.drop_column("liquid", "current_free")
    # ### end Alembic commands ###
