"""add_field_in_posts

Revision ID: 2b641c3855b4
Revises: 18aec85b793c
Create Date: 2024-10-02 20:46:18.109724

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2b641c3855b4"
down_revision: Union[str, None] = "18aec85b793c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "posts",
        sa.Column(
            "url_message_free",
            sa.String(),
            nullable=True,
            comment="Ссылка на сообщение в бесплатной группе",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("posts", "url_message_free")
    # ### end Alembic commands ###
