"""changeSellers

Revision ID: 2d4789450a37
Revises: 95230d68c7e1
Create Date: 2024-11-09 18:13:12.360691

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2d4789450a37"
down_revision: Union[str, None] = "95230d68c7e1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("sellers", sa.Column("created_at", sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sellers", "created_at")
    # ### end Alembic commands ###
