"""add sellers

Revision ID: 325208d0acfb
Revises: 2b641c3855b4
Create Date: 2024-10-11 23:54:01.877625

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "325208d0acfb"
down_revision: Union[str, None] = "2b641c3855b4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sellers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "count",
            sa.Integer(),
            nullable=True,
            comment="Количество продавцов",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("sellers")
    # ### end Alembic commands ###
