"""update_name_field_pull

Revision ID: 4e2a4e2cea26
Revises: 9a45d1869e01
Create Date: 2024-10-01 21:04:30.070689

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4e2a4e2cea26"
down_revision: Union[str, None] = "9a45d1869e01"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "pulls",
        sa.Column(
            "tasks", sa.BigInteger(), nullable=True, comment="Пулл для заданий"
        ),
    )
    op.add_column(
        "pulls",
        sa.Column(
            "current_tasks",
            sa.BigInteger(),
            nullable=True,
            comment="Текущее количество пулла по заданиям",
        ),
    )
    op.drop_column("pulls", "task")
    op.drop_column("pulls", "current_task")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "pulls",
        sa.Column(
            "current_task",
            sa.BIGINT(),
            autoincrement=False,
            nullable=True,
            comment="Текущее количество пулла по заданиям",
        ),
    )
    op.add_column(
        "pulls",
        sa.Column(
            "task",
            sa.BIGINT(),
            autoincrement=False,
            nullable=True,
            comment="Пулл для заданий",
        ),
    )
    op.drop_column("pulls", "current_tasks")
    op.drop_column("pulls", "tasks")
    # ### end Alembic commands ###
