"""add transactions change

Revision ID: 584545436fc9
Revises: 2d4789450a37
Create Date: 2024-12-03 21:30:51.580668

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "584545436fc9"
down_revision: Union[str, None] = "2d4789450a37"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "changes_transactions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("from_сurrency", sa.String(), nullable=False),
        sa.Column("from_amount", sa.Float(), nullable=False),
        sa.Column("to_currency", sa.String(), nullable=False),
        sa.Column("to_amount", sa.Float(), nullable=False),
        sa.Column("transaction_date", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_changes_transactions_id"),
        "changes_transactions",
        ["id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_changes_transactions_id"), table_name="changes_transactions"
    )
    op.drop_table("changes_transactions")
    # ### end Alembic commands ###
