"""add_user_field

Revision ID: 62069051cae6
Revises: 3b0d39f668ae
Create Date: 2024-10-01 22:10:38.401603

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "62069051cae6"
down_revision: Union[str, None] = "3b0d39f668ae"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "count_free_posts",
            sa.Integer(),
            nullable=True,
            comment="Количество бесплатных размещённых постов",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "count_free_posts")
    # ### end Alembic commands ###
