"""add_ban_list

Revision ID: 62b088a0b826
Revises: 1daf24272313
Create Date: 2025-01-16 13:06:50.406209

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "62b088a0b826"
down_revision: Union[str, None] = "1daf24272313"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ban_lists",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "user_name",
            sa.String(),
            nullable=False,
            comment="Никнейм пользователя",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_name"),
    )
    op.create_index(op.f("ix_ban_lists_id"), "ban_lists", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_ban_lists_id"), table_name="ban_lists")
    op.drop_table("ban_lists")
    # ### end Alembic commands ###
