"""add_field_to_tasks

Revision ID: 95230d68c7e1
Revises: 988799ff5dea
Create Date: 2024-10-26 00:20:07.868776

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "95230d68c7e1"
down_revision: Union[str, None] = "988799ff5dea"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tasks",
        sa.Column(
            "reward",
            sa.Integer(),
            nullable=True,
            comment="Награда за выполнение задания",
        ),
    )
    op.drop_index("ix_tasks_url", table_name="tasks")
    op.create_index(op.f("ix_tasks_url"), "tasks", ["url"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tasks_url"), table_name="tasks")
    op.create_index("ix_tasks_url", "tasks", ["url"], unique=False)
    op.drop_column("tasks", "reward")
    # ### end Alembic commands ###
