"""update_type_pull

Revision ID: 9a45d1869e01
Revises: f380e8462797
Create Date: 2024-10-01 20:57:58.515890

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9a45d1869e01"
down_revision: Union[str, None] = "f380e8462797"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "pulls",
        "farming",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_comment="Пулл для фарминга",
        existing_nullable=True,
    )
    op.alter_column(
        "pulls",
        "task",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_comment="Пулл для заданий",
        existing_nullable=True,
    )
    op.alter_column(
        "pulls",
        "friends",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_comment="Пулл для друзей",
        existing_nullable=True,
    )
    op.alter_column(
        "pulls",
        "plan",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_comment="Пулл для краудсорсинга",
        existing_nullable=True,
    )
    op.alter_column(
        "pulls",
        "coins",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_comment="Пулл для монет",
        existing_nullable=True,
    )
    op.alter_column(
        "pulls",
        "current_farming",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_comment="Текущий фарминг",
        existing_nullable=True,
    )
    op.alter_column(
        "pulls",
        "current_task",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_comment="Текущее количество пулла по заданиям",
        existing_nullable=True,
    )
    op.alter_column(
        "pulls",
        "current_friends",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_comment="Текущее количество пулла по друзьям",
        existing_nullable=True,
    )
    op.alter_column(
        "pulls",
        "current_coins",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_comment="Текущее количество пулла по монетам",
        existing_nullable=True,
    )
    op.alter_column(
        "pulls",
        "current_plan",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_comment="Текущее количество пулла по краудсорсингу",
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "pulls",
        "current_plan",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_comment="Текущее количество пулла по краудсорсингу",
        existing_nullable=True,
    )
    op.alter_column(
        "pulls",
        "current_coins",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_comment="Текущее количество пулла по монетам",
        existing_nullable=True,
    )
    op.alter_column(
        "pulls",
        "current_friends",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_comment="Текущее количество пулла по друзьям",
        existing_nullable=True,
    )
    op.alter_column(
        "pulls",
        "current_task",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_comment="Текущее количество пулла по заданиям",
        existing_nullable=True,
    )
    op.alter_column(
        "pulls",
        "current_farming",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_comment="Текущий фарминг",
        existing_nullable=True,
    )
    op.alter_column(
        "pulls",
        "coins",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_comment="Пулл для монет",
        existing_nullable=True,
    )
    op.alter_column(
        "pulls",
        "plan",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_comment="Пулл для краудсорсинга",
        existing_nullable=True,
    )
    op.alter_column(
        "pulls",
        "friends",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_comment="Пулл для друзей",
        existing_nullable=True,
    )
    op.alter_column(
        "pulls",
        "task",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_comment="Пулл для заданий",
        existing_nullable=True,
    )
    op.alter_column(
        "pulls",
        "farming",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_comment="Пулл для фарминга",
        existing_nullable=True,
    )
    # ### end Alembic commands ###
