"""change_sellers

Revision ID: e89c86948774
Revises: 17b7489a0177
Create Date: 2024-10-21 20:59:20.863665

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e89c86948774"
down_revision: Union[str, None] = "17b7489a0177"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sellers",
        sa.Column(
            "subscribes_count",
            sa.Integer(),
            nullable=True,
            comment="Количество пользователей в группе",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sellers", "subscribes_count")
    # ### end Alembic commands ###
