"""add_field_in_transaction

Revision ID: ed83e315f586
Revises: 21caa7b2fa65
Create Date: 2024-10-25 22:25:06.845326

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ed83e315f586"
down_revision: Union[str, None] = "21caa7b2fa65"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "history_transactions", sa.Column("add", sa.Boolean(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("history_transactions", "add")
    # ### end Alembic commands ###
